version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies or performing pre-build tasks"

  pre_build:
    commands:
      - echo "Run pre-build tasks if needed"

  build:
    commands:
      - ./gradlew build

  post_build:
    commands:
      - echo "Run post-build tasks if needed"

artifacts:
  files: '**/*'
  base-directory: 'build/libs'